import React from 'react';
 import Head from 'next/head';
 import RootLayout from './layout';
 export default function App({ Component, pageProps }) { 
return (
 <RootLayout>
     <Head>
 <title>Create Next App</title>
 <meta name="description" content="Generated by create next app" />
 </Head>
  <Component {...pageProps} /> 
  </RootLayout> 
  ); 
}